header:
  version: 14

machine: raspberrypi4-64
distro: poky

repos:
  poky:
    path: layers/poky
    url: https://git.yoctoproject.org/git/poky
    branch: scarthgap
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    path: layers/meta-openembedded
    url: https://github.com/openembedded/meta-openembedded.git
    branch: scarthgap
    layers:
      meta-oe:
      meta-python:
      meta-networking:

  meta-raspberrypi:
    path: layers/meta-raspberrypi
    url: https://git.yoctoproject.org/git/meta-raspberrypi
    branch: scarthgap
    layers:
      .:
