header:
  version: 14
  includes:
    - generic.yml

machine: raspberrypi4-64
distro: poky

repos:
  meta-robot:
    path: layers/meta-robot

  meta-ros:
    path: layers/meta-ros
    url: https://github.com/ros/meta-ros.git
    branch: scarthgap
    layers:
      meta-ros:
